##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= VStest

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -Og

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/filtrage.c \
Core/Src/fmc.c \
Core/Src/gpio.c \
Core/Src/ltdc.c \
Core/Src/main.c \
Core/Src/rtc.c \
Core/Src/screen.c \
Core/Src/sdmmc.c \
Core/Src/stm32f7xx_hal_msp.c \
Core/Src/stm32f7xx_hal_timebase_tim.c \
Core/Src/stm32f7xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32f7xx.c \
Core/Src/touchscreen.c \
Core/Src/usart.c \
Drivers/BSP/Components/adv7533/adv7533.c \
Drivers/BSP/Components/dp83848/dp83848.c \
Drivers/BSP/Components/exc7200/exc7200.c \
Drivers/BSP/Components/ft3x67/ft3x67.c \
Drivers/BSP/Components/ft5336/ft5336.c \
Drivers/BSP/Components/ft6x06/ft6x06.c \
Drivers/BSP/Components/lan8742/lan8742.c \
Drivers/BSP/Components/mfxstm32l152/mfxstm32l152.c \
Drivers/BSP/Components/nt35510/nt35510.c \
Drivers/BSP/Components/otm8009a/otm8009a.c \
Drivers/BSP/Components/ov5640/ov5640.c \
Drivers/BSP/Components/ov9655/ov9655.c \
Drivers/BSP/Components/s5k5cag/s5k5cag.c \
Drivers/BSP/Components/st7735/st7735.c \
Drivers/BSP/Components/st7789h2/st7789h2.c \
Drivers/BSP/Components/stmpe811/stmpe811.c \
Drivers/BSP/Components/ts3510/ts3510.c \
Drivers/BSP/Components/wm8994/wm8994.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_audio.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_eeprom.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_lcd.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_qspi.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_sdram.c \
Drivers/BSP/STM32F769I-Discovery/stm32f769i_discovery_ts.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_add_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q7.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f32.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q15.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q31.c \
Drivers/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q7.c \
Drivers/CMSIS/DSP/Source/CommonTables/arm_common_tables.c \
Drivers/CMSIS/DSP/Source/CommonTables/arm_const_structs.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_conj_q31.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_dot_prod_q31.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_q31.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mag_squared_q31.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_cmplx_q31.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_f32.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q15.c \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions/arm_cmplx_mult_real_q31.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_f32.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q15.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_init_q31.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_f32.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q15.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_pid_reset_q31.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_f32.c \
Drivers/CMSIS/DSP/Source/ControllerFunctions/arm_sin_cos_q31.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_cos_f32.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_cos_q15.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_cos_q31.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_sin_f32.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_sin_q15.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_sin_q31.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_sqrt_q15.c \
Drivers/CMSIS/DSP/Source/FastMathFunctions/arm_sqrt_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
Drivers/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.c \
Drivers/CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
Drivers/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_copy_f32.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_copy_q15.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_copy_q31.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_copy_q7.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_fill_f32.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_fill_q15.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_fill_q31.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_fill_q7.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q15.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q31.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_float_to_q7.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_float.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_q31.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q15_to_q7.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_float.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_q15.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q31_to_q7.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_float.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_q15.c \
Drivers/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix2_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix4_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_cfft_radix8_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_init_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_dct4_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_f32.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_init_q31.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_q15.c \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_rfft_q31.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c \
Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_sdmmc.c \
FATFS/App/fatfs.c \
FATFS/Target/bsp_driver_sd.c \
FATFS/Target/fatfs_platform.c \
FATFS/Target/sd_diskio.c \
Middlewares/Third_Party/FatFs/src/diskio.c \
Middlewares/Third_Party/FatFs/src/ff.c \
Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
Middlewares/Third_Party/FatFs/src/option/syscall.c


CPP_SOURCES = \


# ASM sources
ASM_SOURCES =  \
Drivers/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.S \
startup_stm32f769xx.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S

# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F769xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F769xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/BSP/Components/Common \
-IDrivers/BSP/Components/adv7533 \
-IDrivers/BSP/Components/ampire480272 \
-IDrivers/BSP/Components/ampire640480 \
-IDrivers/BSP/Components/dp83848 \
-IDrivers/BSP/Components/exc7200 \
-IDrivers/BSP/Components/ft3x67 \
-IDrivers/BSP/Components/ft5336 \
-IDrivers/BSP/Components/ft6x06 \
-IDrivers/BSP/Components/lan8742 \
-IDrivers/BSP/Components/mfxstm32l152 \
-IDrivers/BSP/Components/mx25l512 \
-IDrivers/BSP/Components/n25q128a \
-IDrivers/BSP/Components/n25q512a \
-IDrivers/BSP/Components/nt35510 \
-IDrivers/BSP/Components/otm8009a \
-IDrivers/BSP/Components/ov5640 \
-IDrivers/BSP/Components/ov9655 \
-IDrivers/BSP/Components/rk043fn48h \
-IDrivers/BSP/Components/s5k5cag \
-IDrivers/BSP/Components/st7735 \
-IDrivers/BSP/Components/st7789h2 \
-IDrivers/BSP/Components/stmpe811 \
-IDrivers/BSP/Components/ts3510 \
-IDrivers/BSP/Components/w25q128j \
-IDrivers/BSP/Components/wm8994 \
-IDrivers/BSP/STM32F769I-Discovery \
-IDrivers/CMSIS/DSP/Include \
-IDrivers/CMSIS/Device/ST/STM32F7xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F7xx_HAL_Driver/Inc \
-IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy \
-IFATFS/App \
-IFATFS/Target \
-IMiddlewares/Third_Party/FatFs/src



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += -fno-exceptions -fno-rtti 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F769NIHx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(subst ../,parent,$(1))))))

REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c md $(call convert_to_windows_path,$(1))
endif



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CPP_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

# the tree of folders which needs to be present based on the object files
BUILD_TREE = $(sort $(dir $(OBJECTS)))

# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(BUILD_TREE)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(BUILD_TREE)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(BUILD_TREE)
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(BUILD_DIRECTORY)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIRECTORY)/%.hex: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(HEX) $< $@

$(BUILD_DIRECTORY)/%.bin: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(BIN) $< $@

$(BUILD_DIRECTORY)/%.lss: $(BUILD_DIRECTORY)/%.elf | $(BUILD_DIRECTORY)
	$(LSS) $< > $@

$(BUILD_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_TREE):
	$(call mkdir_function, $@)

#######################################
# all
#######################################
# default action: build all
all:
	$(BUILD_DIRECTORY)/$(TARGET).elf 
	$(BUILD_DIRECTORY)/$(TARGET).hex 
	$(BUILD_DIRECTORY)/$(TARGET).bin 
	$(BUILD_DIRECTORY)/$(TARGET).lss 


flash: $(BUILD_DIRECTORY)/$(TARGET).elf
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(BUILD_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIRECTORY)/$(TARGET).elf
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32f7x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIRECTORY)/*.d)

# *** EOF ***